FROM golang:1.10.3
COPY . /go/src/github.com/kelseyhightower/grafeas-tutorial/image-signature-webhook/
WORKDIR /go/src/github.com/kelseyhightower/grafeas-tutorial/image-signature-webhook
RUN CGO_ENABLED=0 go build -o image-signature-webhook .

FROM alpine:latest
WORKDIR /
COPY --from=0 /go/src/github.com/kelseyhightower/grafeas-tutorial/image-signature-webhook/image-signature-webhook /image-signature-webhook
EXPOSE 443
ENTRYPOINT ["/image-signature-webhook"]
